# Generated by Django 5.1.1 on 2024-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_risk_impact_remove_risk_likelyhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigation',
            field=models.CharField(max_length=100),
        ),
    ]
