# Generated by Django 5.1.1 on 2024-10-17 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_risk_description_alter_risk_mitigation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='author',
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('surname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cell_phone', models.CharField(max_length=200)),
                ('medical_aid', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
