# Generated by Django 5.1.1 on 2024-10-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_risk_author_patient_delete_incident_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='cell_phone',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='city',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medical_aid',
            new_name='province',
        ),
    ]
